# =========================
# ADMIN LOGS
# =========================
colorscheme:davit-admin
# Inherit base + add admin-only keywords
cs_re:red:ADMIN|SECURITY|ACCESS_DENIED
cs_re:magenta:USER_LOGIN|AUTH
# You can also add column-specific overrides here if admin logs ever diverge
# === MODE / keyword coloring ===
cs_re:yellow:stage
cs_re:green:prod
cs_re:213,,blink:dev
# === SPECIAL CHARS ===
cs_re:magenta,,bold:\]|\[
# col1 (timestamp)
cs_re:195:^[0-9 :\.\-][^|]+
# col2 (user)
cs_re_s:198:^[^|]+ \| ([^|]+) \| [^|]+ \| [^|]+ \| [^|]+ \| [^|]+:[^|]+ \| \[[^|]+:[^|]+\] \| \[[^|]+\] \| .+
# col3 (level)
cs_re_s:cyan:^.+ \| .+ \| (.+) \| .+ \| .+ \| .+:.+ \| \[.*:.+\] \| \[.+\] \| .+
# col4 (category)
cs_re_s:magenta:^.+ \| .+ \| .+ \| (.+) \| .+ \| .+:.+ \| \[.*:.+\] \| \[.+\] \| .+
# col5 (category)
cs_re_s:red:^.+ \| .+ \| .+ \| .+ \| (.+) \| .+:.+ \| \[.*:.+\] \| \[.+\] \| .+
# col6 (MODE)
cs_re_s:blue:^.+ \| .+ \| .+ \| .+ \| .+ \| (.+):.+ \| \[.*:.+\] \| \[.+\] \| .+
# col7 (PID)
cs_re_s:blue:^.+ \| .+ \| .+ \| .+ \| .+ \| .+:.+ \| \[(.*):.+\] \| \[.+\] \| .+
# col8 (file)
cs_re_s:green:^.+ \| .+ \| .+ \| .+ \| .+ \| .+:.+ \| \[.*:.+\] \| \[(.+)\] \| .+
# col9 (message)
cs_re_s:191:^.+ \| .+ \| .+ \| .+ \| .+ \| .+:.+ \| \[.*:.+\] \| \[.+\] \| (.+)

# default colorschemes:
scheme:davit-admin:/opt/davit/logs/*-admin.log
